name: "⚡ EnigMano Win11 + CRD 6H Session"

on:
  workflow_dispatch:

jobs:
  deploy-enigmano:
    runs-on: windows-latest
    timeout-minutes: 360  # 6 heures max

    steps:
      - name: 📥 Install Chrome Remote Desktop
        shell: pwsh
        run: |
          $crdInstaller = "$env:TEMP\crdhost.msi"
          Invoke-WebRequest "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile $crdInstaller
          Start-Process msiexec.exe -ArgumentList "/i `"$crdInstaller`" /quiet /norestart" -Wait
          Remove-Item $crdInstaller -Force
          Write-Host "✅ Chrome Remote Desktop installed."

      - name: ⚔️ Start Chrome Remote Desktop Host
        shell: pwsh
        run: |
          $exe = "${Env:ProgramFiles(x86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"

          if (-not (Test-Path $exe)) {
            Write-Error "❌ CRD executable not found at $exe"
            exit 1
          }

          & $exe `
            --code="⚡TON_CODE_ICI⚡" `
            --redirect-url="https://remotedesktop.google.com/_/oauthredirect" `
            --name=$Env:COMPUTERNAME `
            --pin=123456

      - name: ⏳ Keep Alive 6H
        shell: pwsh
        run: |
          Write-Host "🔄 EnigMano KeepAlive started (6h max)..."
          Start-Sleep -Seconds 21600
          Write-Host "✅ Session finished after 6 hours."
