name: "⚡ EnigMano Win11 + CRD Deployment"

on:
  workflow_dispatch:

jobs:
  deploy-enigmano:
    runs-on: windows-latest

    steps:
      - name: 📌 Deployment Parameters
        shell: pwsh
        run: |
          Write-Host "==============================================="
          Write-Host "🔹 EnigMano Instance : 1"
          Write-Host "📦 Repository        : $env:GITHUB_REPOSITORY"
          Write-Host "==============================================="

      - name: 📥 Install Chrome Remote Desktop
        shell: pwsh
        run: |
          $crdInstaller = "$env:TEMP\crdhost.msi"
          Invoke-WebRequest "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile $crdInstaller
          Start-Process msiexec.exe -ArgumentList "/i `"$crdInstaller`" /quiet /norestart" -Wait
          Remove-Item $crdInstaller -Force
          Write-Host "✅ Chrome Remote Desktop installed."

      - name: ⚔️ Start Chrome Remote Desktop Host
        shell: pwsh
        run: |
          $exe = "${Env:ProgramFiles(x86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"

          if (-not (Test-Path $exe)) {
            Write-Error "❌ CRD executable not found at $exe"
            exit 1
          }

          & $exe `
            --code="4/0AVMBsJgvn4ivlC6UOo1UOLBNymcT2N1W1W1Rdc-gXSm2pr0CSJ93HdYUD6eDJWeUoYaS0A" `
            --redirect-url="https://remotedesktop.google.com/_/oauthredirect" `
            --name=$Env:COMPUTERNAME `
            --pin=123456

      - name: 🕒 Keep Alive 6h Timer
        shell: pwsh
        run: |
          $total = 21600
          for ($s = $total; $s -ge 0; $s--) {
            if ($s % 60 -eq 0) {  # Affiche chaque minute
              Write-Host "$s secondes restantes..."
            }
            Start-Sleep -Seconds 1
          }
          Write-Host "⏰ 6 heures écoulées ! Fin du timer."

      - name: 💠 Final Status
        if: always()
        shell: pwsh
        run: |
          Write-Host "✅ EnigMano Instance deployed with Chrome Remote Desktop."
          Write-Host "🔋 Powered by: CRD + GitHub Actions"
